artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1ZgXJfs_QH5EN31siynIReZDv21wHRT4W/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  split_dir: artifacts/data_ingestion/CT-scan-data
  train_dir: artifacts/data_ingestion/CT-scan-data/train
  val_dir: artifacts/data_ingestion/CT-scan-data/val
  test_dir: artifacts/data_ingestion/CT-scan-data/test
  split_ratio:
    train: 0.7
    val: 0.15
    test: 0.15

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

evaluation:
  mlflow_uri: https://dagshub.com/sujalvairagi/sujalvairagi-CI-CD_chest_cancer_with_vgg-16.mlflow

ct_gate:
  root_dir: artifacts/ct_gate
  data_dir: artifacts/ct_gate/data
  model_path: artifacts/ct_gate/ct_gate_model.h5
  mlflow_uri: https://dagshub.com/sujalvairagi/sujalvairagi-CI-CD_chest_cancer_with_vgg-16.mlflow